[package]
name = "bitmex"
version = "0.1.6-alpha.0"
authors = ["Weiy√ºen Wu <doomsplayer@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Rust Library for the BitMEX API (Async)"
keywords = ["cryptocurrency", "trading", "bitmex", "async"]
documentation = "https://docs.rs/crate/bitmex"
repository = "https://github.com/dovahcrow/bitmex-rs"
readme = "README.md"
edition = "2018"


[dependencies]
hyper = "0.12"
hyper-tls = "0.3"

url = "1"
futures = "0.1"
tokio = "0.1"

failure = "0.1"
log = "0.4"

serde = "1"
serde_json = "1"
serde_derive = "1"

chrono = { version = "0.4", features = ["serde"] }

hex = "0.3"
ring = "0.13"

uuid = { version = "0.7", features = ["serde"] }
# maplit = "1"

tungstenite = "0.6"
tokio-tungstenite = "0.6"
lazy_static = "1"

[features]
dev = []

[dev-dependencies]
dotenv = "0.13"
env_logger = "0.6"